#!/usr/bin/env bun
/**
 * Generate src/web/client-assets.gen.ts from the built web client.
 *
 * Each file under src/web/client/dist is imported with `{ type: 'file' }` so
 * `bun build --compile` embeds it into the binary. The same module also works
 * when running from source (the import paths resolve on disk).
 *
 * Run automatically by `bun run web:build`. Vite hashes asset filenames on
 * every build, so this must be regenerated alongside it.
 */

import * as fs from 'node:fs'
import * as path from 'node:path'

const root = path.join(import.meta.dir, '..')
const distDir = path.join(root, 'src', 'web', 'client', 'dist')
const outFile = path.join(root, 'src', 'web', 'client-assets.gen.ts')

function walk(dir: string): string[] {
  const out: string[] = []
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) out.push(...walk(full))
    else out.push(full)
  }
  return out
}

if (!fs.existsSync(distDir)) {
  console.error(`[gen-web-assets] ${distDir} not found — run the Vite build first.`)
  process.exit(1)
}

const files = walk(distDir).sort()
const lines: string[] = [
  '// AUTO-GENERATED by scripts/gen-web-assets.ts — do not edit.',
  '// Regenerated by `bun run web:build`. Embedded into the compiled binary.',
  '',
]
const entries: string[] = []

files.forEach((abs, i) => {
  const rel = path.relative(distDir, abs).split(path.sep).join('/')
  const ident = `a${i}`
  // Import path is relative to this generated file (src/web/client-assets.gen.ts).
  lines.push(`import ${ident} from './client/dist/${rel}' with { type: 'file' }`)
  entries.push(`  '/${rel}': ${ident},`)
})

lines.push('', 'export const WEB_ASSETS: Record<string, string> = {', ...entries, '}', '')

fs.writeFileSync(outFile, lines.join('\n'))
console.log(`[gen-web-assets] wrote ${path.relative(root, outFile)} (${files.length} files)`)
